// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtTWN-8Mb1yb32JAKnA-F2UzCEdtnVKaw',
    appId: '1:513587324270:web:fdb3c1cdbbe5f273378d7f',
    messagingSenderId: '513587324270',
    projectId: 'pns-order',
    authDomain: 'pns-order.firebaseapp.com',
    storageBucket: 'pns-order.appspot.com',
    measurementId: 'G-F7NJEBSQJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI6C8FVg74M1mD_23DhEE83HNfXGg-Z4k',
    appId: '1:513587324270:android:39c394e57a418db4378d7f',
    messagingSenderId: '513587324270',
    projectId: 'pns-order',
    storageBucket: 'pns-order.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1mTcFgqeD0r2K5J0m7o76woVskcKoOU0',
    appId: '1:513587324270:ios:d5064da121cd2879378d7f',
    messagingSenderId: '513587324270',
    projectId: 'pns-order',
    storageBucket: 'pns-order.appspot.com',
    iosBundleId: 'com.example.dad3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1mTcFgqeD0r2K5J0m7o76woVskcKoOU0',
    appId: '1:513587324270:ios:6f83199975ed5702378d7f',
    messagingSenderId: '513587324270',
    projectId: 'pns-order',
    storageBucket: 'pns-order.appspot.com',
    iosBundleId: 'com.example.dad3.RunnerTests',
  );
}
